### ISSUE TITLE
support for bevdet dev2.0

### ISSUE THREAD

**Issue by toyot-li** [Hale423/bev_align_plugin#1]
@HaohaoNJU Thanks for your awesome work, but this repo seems to be based on BEVDet master, which is deprecated now due to inferior efficiency. Would you like to also provide a version compatible with dev2.0? Thanks.

**Comment by Hale423** [comment]
I also provided `bev_align_fast`,  see the examples in README
`from mmdet3d.ops import voxel_pool, voxel_align, voxel_align_fast`

**Comment by toyot-li** [comment]
@HaohaoNJU Hi, I tried voxel_align_fast with BEVDet dev2.0 on nuScenes, but the performance is extremely low. Specifically, the modification is
```diff
 @NECKS.register_module()
@@ -268,9 +269,11 @@ class LSSViewTransformer(BaseModule):
             bev_feat = bev_feat.squeeze(2)
         else:
             coor = self.get_lidar_coor(*input[1:7])
-            bev_feat = self.voxel_pooling_v2(
-                coor, depth.view(B, N, self.D, H, W),
-                tran_feat.view(B, N, self.out_channels, H, W))
+            #bev_feat = self.voxel_pooling_v2(
+            #    coor, depth.view(B, N, self.D, H, W),
+            #    tran_feat.view(B, N, self.out_channels, H, W))
+            bev_feat = voxel_align_fast(depth.view(B, N, self.D, H, W),
+                tran_feat.view(B, N, self.out_channels, H, W), coor, int(self.grid_size[1]), int(self.grid_size[0]))
         return bev_feat, depth
```
Is there anything wrong with that? Thanks.

**Comment by Hale423** [comment]
What do you mean by performance, is it running slower or the detection metrics are lower ?
Did you apply voxel_align and retrain the model, or did you just run an inference with voxel_align plugin on model weights trained with voxel_pooling ?

**Comment by toyot-li** [comment]
Performance means accuracy, i.e., NDS 12.4%, mAP 1.1%. The model is trained from scratch with `voxel_align_fast` and inference is consistent with the training model architecture.

**Comment by Hale423** [comment]
Hi, `voxel_align`   has been tested in our practices and has proven to be effective,   however, `voxel_align_fast` has not, can you try it with `voxel_align` for the moment?  The end-to-end training speed doesn't show much difference. Here is how to use `voxel_align` :
```
from mmdet3d.ops import voxel_pool, voxel_align, voxel_align_fast
    def view_transform(self, input, depth, tran_feat, bev_align = True):
        # ================================Voxel Align=====================================
        B, N, C, H, W = input[0].shape
        coor = self.get_lidar_coor(*input[1:7]).reshape(B,N, self.D, H, W, 3)
        # Lift-Splat
        feat = tran_feat.view(B, N, self.out_channels, H, W)
        depth = depth.view(B, N, self.D, H, W)
        bev_h = int(self.grid_size[1])
        bev_w = int(self.grid_size[0])
        if bev_align:
            volume = depth.unsqueeze(2) * feat.unsqueeze(3)
            volume = volume.permute(0, 1, 3, 4, 5, 2)
            bev_feat = voxel_align(volume, coor, bev_h, bev_w)
            bev_feat = bev_feat.squeeze(2)
```

**Comment by toyot-li** [comment]
@HaohaoNJU Thanks for your prompt reply and detailed instructions!
1. I have understood how to use `voxel_align` from your provided examples in `README`. As implied by the title, what takes me here is actually a desire for a fast version, like `bevpoolv2`. I will appreciate it if you could further validate the corresponding `voxel_align_fast`.
2. I am trying `voxel_align` for e2e training now, whose speed is indeed similar, but I think there still exists a large `volume` to be produced, understanding from the optimization of `bevpoolv2`. Correct me if I miss anything.
3. BTW, `bev_feat = bev_feat.squeeze(2)` seems not to be necessary in the above snippet if I understand correctly.

**Comment by Hale423** [comment]
1 & 2 .  A  fast version of the `voxel_align` plugin is itself indeed accelerated and saved the GPU mems, however, this op doesn't take up as much proportion of the whole computation graph as we previously assumed, so the end-to-end training speed makes almost no difference, that's why I didn't validate `voxel_align_fast` previously.

3. Just neglect it, `...squeeze...` is copied from the original block of code

**Comment by toyot-li** [comment]
@HaohaoNJU The NDS and mAP with `voxel_align` is still as low as I stated above with `voxel_align_fast`. In addition, their training losses are almost the same during the whole training process, much higher than the default BEVDepth (I use bevdet-r50-depth-cbgs.py for all ablation experiments).

**Comment by Hale423** [comment]
Oh I saw the problems, pls convert `coor` as float indexs , before you sent `coor` into `voxel_align`:
` coor = ((coor - self.grid_lower_bound.to(coor)) / self.grid_interval.to(coor))`

**Comment by toyot-li** [comment]
Yes, that's the point. The training loss is healthy now. Thanks.
